### ISSUE TITLE
[Bug] .NET Core error when running the app

### ISSUE THREAD

**Issue by pidgeon777** [codingyourlife/fritzbox.reconnect#1] opened 2019-08-04 13:12 UTC
Hello, when I try to run the program on Windows 7 x64 SP1, then the following error appears:

````
C:\fritzbox.reconnect_win10-x64>ReconnectFritz.exe
Error:
  An assembly specified in the application dependencies manifest (ReconnectFritz.deps.json) was not found:
    package: 'runtime.win-x64.Microsoft.NETCore.App', version: '2.1.6'
    path: 'runtimes/win-x64/lib/netcoreapp2.1/Microsoft.CSharp.dll'
````

What should I do to fix the problem? Thank you.

**Comment by codingyourlife** [comment] 2019-08-05 10:33
Does it work when pressing run in Visual Studio via the green Debug Button? Then I guess the problem is the publish settings (there are none). It searches for a CSharp.dll and it's a .NET **CORE** application. You can either install .NET CORE (noone does that) or publish it as self-contained. I've added publish settings with the self-contained option enabled and pushed my changes. I also upgraded .NET Core to latest stable version.

So please pull the latest version from Github, say right click Clean (or delete the bin folder) and right click Publish (and click publish button) on the project in Visual Studio. The publish folder in ./bin/Release/netcoreapp2.2/publish/ should be the relevant one containing ReconnectFritz.exe.

Disclaimer: I haven't tested my changes myself because I'm currently not behind of a FritzBox and didn't feel like I wanted to take the risk of talking FritzBox Langauge to another Router ^^. But I didn't want to let you wait. So please tell me if it worked :)

**Comment by pidgeon777** [comment] 2019-08-05 12:03
Hello, first of all, thanks for the prompt reply. Unfortunately, Visual Studio isn't installed on my PC, so I have no chance to test the method you suggested. Maybe I should try again by installing a specific Microsoft Package, as it happens for example with Microsoft .NET Framework?

**Comment by codingyourlife** [comment] 2019-08-06 07:49
Ah ok. I forgot that I've uploaded a packed release. I've meanwhilte tested the exe in my network and it works. I've now uploaded it as v2 Release and marked the old one as defect
https://github.com/codingyourlife/fritzbox.reconnect/releases/tag/2

Tell me if this works for you :)

**Comment by pidgeon777** [comment] 2019-08-06 18:44
Hello, thanks again for the prompt reply. I just tried your latest release, and what can I say: it works perfectly!

Personally, I'm amazed by the reconnection speed I'm now able to reach: I wouldn't have expected this tool to operate so fast! Even faster than my previous reconnect script for the ADSL line (now I'm on FTTH). Amazing work.

**Comment by codingyourlife** [comment] 2019-08-06 21:42
Glad to hear that :) - Closing...

**Closed as completed by codingyourlife** 2019-08-06 21:42 UTC
